#################################################################
# SpreeCommerce Deployment Configuration for Render.com
#################################################################

# List all services *except* PostgreSQL databases here
services:
  # A web service for SpreeCommerce (Ruby on Rails)
  - type: web
    runtime: ruby
    name: spreecommerce
    repo: https://github.com/jhanitesh10/spree # Use your repo
    numInstances: 3   # Manual scaling configuration. Default: 1
    region: frankfurt # You can choose other regions (e.g., oregon)
    plan: standard    # Change to "starter" for free tier if small-scale
    branch: main      # Default: master
    buildCommand: |
      bundle install
      yarn install # if using webpacker for assets
    preDeployCommand: |
      bundle exec rake db:create
      bundle exec rake db:migrate
      bundle exec rake spree:load_sample_data # Optional, remove if not needed
    startCommand: |
      bundle exec rails server -b '0.0.0.0' -p $PORT
    autoDeploy: true # Enable auto-deployment when changes are pushed to Git
    envVars: # Environment variables
      - key: DATABASE_URL
        fromDatabase:
          name: spree-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: spree-redis
          type: redis
          property: host
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: 'true'
      - key: SPAWN_WORKERS
        value: 'true' # For background workers, if used
